import type { TestPrompt } from './types'

// 20 hand-written test prompts covering the two model profiles the backend actually
// supports ("student" / "personnel" -- see GET /v1/model-profiles), a spread of
// aspect_ratio/resolution combinations, and a handful of deliberately awkward inputs
// (very long text, Thai-only, English-only, mixed language, special characters, an
// empty-ish negative_prompt) so a load test also exercises input-handling, not just
// happy-path throughput. category is shown in the results table / stats breakdown so
// you can see whether e.g. "long_text" prompts are slower or fail more than "headshot".

export const PROMPT_BANK: TestPrompt[] = [
  {
    id: 'p01',
    category: 'personnel_headshot',
    text: 'professional corporate headshot of a Thai university staff member, navy blazer, neutral grey studio background, soft key light, confident friendly expression, sharp focus on eyes',
    negativePrompt: 'blurry, harsh shadows, extra limbs, distorted face, watermark',
    aspectRatio: '3:4',
    resolution: '2K',
    modelProfile: 'personnel',
    note: 'baseline personnel ID-photo style',
  },
  {
    id: 'p02',
    category: 'personnel_headshot',
    text: 'formal ID badge photo, Thai office worker in white shirt and tie, plain light blue background, front-facing, even lighting, passport-photo composition',
    negativePrompt: 'sunglasses, hat, side profile, motion blur',
    aspectRatio: '1:1',
    resolution: '1K',
    modelProfile: 'personnel',
  },
  {
    id: 'p03',
    category: 'personnel_group',
    text: 'small team of five university staff members standing together in a modern office lobby, smiling, business casual attire, natural window light',
    negativePrompt: 'deformed hands, duplicate people, low detail faces',
    aspectRatio: '16:9',
    resolution: '2K',
    modelProfile: 'personnel',
  },
  {
    id: 'p04',
    category: 'student_portrait',
    text: 'university student in graduation gown holding a diploma, joyful expression, campus courtyard with trees in the background, golden hour lighting',
    negativePrompt: 'blurry background, extra fingers, warped diploma text',
    aspectRatio: '3:4',
    resolution: '2K',
    modelProfile: 'student',
  },
  {
    id: 'p05',
    category: 'student_portrait',
    text: 'casual student ID photo, friendly smile, university polo shirt, plain white background, soft studio lighting',
    negativePrompt: 'harsh shadow, off-center, closed eyes',
    aspectRatio: '1:1',
    resolution: '1K',
    modelProfile: 'student',
  },
  {
    id: 'p06',
    category: 'student_activity',
    text: 'group of students collaborating around a laptop in a bright university library, engaged expressions, shallow depth of field',
    negativePrompt: 'text artifacts, distorted laptop screen, extra hands',
    aspectRatio: '4:3',
    resolution: '1K',
    modelProfile: 'student',
  },
  {
    id: 'p07',
    category: 'event_poster',
    text: 'modern minimalist poster background for a university open-house event, blue and gold color palette, abstract geometric shapes, empty space at the top for a headline',
    negativePrompt: 'text, watermark, cluttered composition',
    aspectRatio: '9:16',
    resolution: '2K',
    modelProfile: 'personnel',
  },
  {
    id: 'p08',
    category: 'event_poster',
    text: 'vibrant banner background celebrating a university sports day, dynamic diagonal color stripes in maroon and white, energetic motion lines, room for a title',
    negativePrompt: 'photorealistic people, text, logo',
    aspectRatio: '16:9',
    resolution: '2K',
    modelProfile: 'personnel',
  },
  {
    id: 'p09',
    category: 'certificate_bg',
    text: 'elegant certificate background, cream paper texture with a subtle gold border ornament, formal and academic feel, empty center for text',
    negativePrompt: 'photograph, people, harsh colors',
    aspectRatio: '4:3',
    resolution: '1K',
    modelProfile: 'personnel',
  },
  {
    id: 'p10',
    category: 'campus_scene',
    text: 'wide establishing shot of a university campus building at sunset, warm light reflecting off glass windows, students walking in the distance, cinematic composition',
    negativePrompt: 'low resolution, oversaturated, lens flare artifacts',
    aspectRatio: '16:9',
    resolution: '2K',
    modelProfile: 'student',
  },
  {
    id: 'thai01',
    category: 'thai_only',
    text: 'ภาพถ่ายบุคลากรมหาวิทยาลัยสวมเสื้อเชิ้ตสีขาว ยิ้มอย่างเป็นมิตร พื้นหลังสีเทาอ่อนแบบสตูดิโอ แสงนุ่มสม่ำเสมอ ความคมชัดสูงที่ดวงตา',
    negativePrompt: 'ภาพเบลอ เงาจัดจ้าน แขนขาผิดรูป',
    aspectRatio: '3:4',
    resolution: '1K',
    modelProfile: 'personnel',
    note: 'ทดสอบ prompt ภาษาไทยล้วน',
  },
  {
    id: 'thai02',
    category: 'thai_only',
    text: 'นักศึกษาสวมชุดครุยรับปริญญา ยืนยิ้มถือใบปริญญาบัตร ฉากหลังเป็นสวนในมหาวิทยาลัยยามเย็น แสงสีทองอบอุ่น',
    negativePrompt: 'พื้นหลังเบลอเกินไป นิ้วมือผิดรูป',
    aspectRatio: '3:4',
    resolution: '2K',
    modelProfile: 'student',
  },
  {
    id: 'mixed01',
    category: 'mixed_language',
    text: 'official staff photo (ภาพทางการของบุคลากร) wearing a formal Thai academic gown, standing in front of the university logo wall, professional lighting, high detail',
    negativePrompt: 'blurry logo, distorted text on wall, low detail',
    aspectRatio: '1:1',
    resolution: '2K',
    modelProfile: 'personnel',
    note: 'ทดสอบ prompt ผสมไทย-อังกฤษในข้อความเดียว',
  },
  {
    id: 'edge_long01',
    category: 'long_text',
    text: [
      'extremely detailed professional portrait of a university staff member for an official personnel directory photo,',
      'wearing a tailored dark navy blazer over a crisp white collared shirt, seated in a modern minimalist office with',
      'soft diffused daylight coming from a large window on the left, a small potted plant and a neatly organized desk',
      'with a laptop and a few papers visible but out of focus in the background, the subject has a warm approachable',
      'smile, direct eye contact with the camera, shallow depth of field with the face in tack-sharp focus, color graded',
      'with slightly warm neutral tones typical of corporate photography, shot on a full-frame camera with an 85mm',
      'portrait lens at f/2.0, soft catchlights visible in the eyes, natural skin texture preserved, no over-smoothing,',
      'high dynamic range, professional retouching quality suitable for print on an employee ID badge and the university',
      'staff directory web page',
    ].join(' '),
    negativePrompt: 'over-smoothed skin, plastic look, extra fingers, asymmetrical face, blown-out highlights, harsh shadows, low detail, jpeg artifacts',
    aspectRatio: '3:4',
    resolution: '2K',
    modelProfile: 'personnel',
    note: 'stress test: very long text field, checks server-side truncation/handling',
  },
  {
    id: 'edge_short01',
    category: 'minimal_text',
    text: 'staff photo',
    aspectRatio: '1:1',
    resolution: '1K',
    modelProfile: 'personnel',
    note: 'stress test: minimal prompt with no negative_prompt at all',
  },
  {
    id: 'edge_special01',
    category: 'special_chars',
    text: 'staff headshot for badge #A-042 (dept: R&D) — smiling, 50mm lens, "studio" background @ 100% focus; email: staff@example.edu — high-res!!',
    negativePrompt: 'watermark, text overlay, low-res',
    aspectRatio: '1:1',
    resolution: '1K',
    modelProfile: 'personnel',
    note: 'stress test: punctuation/symbols that sometimes break prompt parsers (#, &, —, @, quotes, !!)',
  },
  {
    id: 'edge_aspect01',
    category: 'unusual_aspect',
    text: 'ultra-wide panoramic photo of a university campus quad full of students during a festival, banners and tents visible, daytime, lively atmosphere',
    negativePrompt: 'distorted perspective, warped faces at edges',
    aspectRatio: '21:9',
    resolution: '2K',
    modelProfile: 'student',
    note: 'stress test: aspect_ratio value the backend likely does not recognize -- should silently fall back to 1:1 per app/adapters/comfyui/live.py; watch for that in the output',
  },
  {
    id: 'edge_profile01',
    category: 'invalid_profile_probe',
    text: 'quick personnel headshot test',
    aspectRatio: '1:1',
    resolution: '1K',
    modelProfile: 'personnel',
    note: 'intentionally pair with a deliberately wrong model_profile override in the UI (e.g. "staff") to confirm the 400 path -- see Scenario panel "probe invalid model_profile" toggle',
  },
  {
    id: 'p19',
    category: 'personnel_headshot',
    text: 'friendly professional headshot of a Thai university lecturer, light grey cardigan, warm smile, blurred bookshelf background, natural lighting',
    negativePrompt: 'harsh flash, red eye, distorted glasses',
    aspectRatio: '4:3',
    resolution: '1K',
    modelProfile: 'personnel',
  },
  {
    id: 'p20',
    category: 'student_portrait',
    text: 'student volunteer wearing an event staff lanyard and t-shirt, standing at a registration desk, cheerful expression, indoor event lighting',
    negativePrompt: 'blurry lanyard text, distorted hands',
    aspectRatio: '3:4',
    resolution: '1K',
    modelProfile: 'student',
  },
]

export function pickPrompt(index: number): TestPrompt {
  return PROMPT_BANK[index % PROMPT_BANK.length]
}

export function getPromptById(id: string): TestPrompt | undefined {
  return PROMPT_BANK.find((p) => p.id === id)
}
